apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - targetPort: 80
    name: http
    port: 80
  - targetPort: 22
    name: ssh
    port: 22
  - targetPort: 443
    name: https
    port: 443
  type: LoadBalancer
